apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frameworks
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    {{- range .Values.ingress.fastapiExtraHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: fastapi
                port:
                  name: http
    {{- end }}
    {{- range $app, $host := .Values.ingress.hosts }}
    - host: {{ $host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ $app }}
                port:
                  name: http
    {{- end }}
